# Generated by Django 3.0.5 on 2022-01-11 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyName', models.CharField(max_length=100)),
                ('currencyCode', models.CharField(default='UGX', max_length=10, unique=True)),
                ('currencyStatus', models.CharField(max_length=20)),
                ('regDate', models.DateField(default=django.utils.timezone.now)),
                ('date1', models.DateTimeField(auto_now_add=True)),
                ('regBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
