# Generated by Django 3.0.5 on 2022-01-11 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposits',
            fields=[
                ('deposit_id', models.CharField(editable=False, max_length=266, primary_key=True, serialize=False)),
                ('accountNo', models.CharField(max_length=266)),
                ('accountName', models.CharField(max_length=266)),
                ('accountType', models.CharField(max_length=100)),
                ('accountCurrency', models.CharField(max_length=10)),
                ('ninNumber', models.CharField(blank=True, max_length=266)),
                ('contact', models.CharField(max_length=20)),
                ('oldBalance', models.FloatField(default=0)),
                ('charges', models.IntegerField(blank=True, default=0)),
                ('depositAmount', models.FloatField()),
                ('newBalance', models.FloatField()),
                ('depositDate', models.DateField()),
                ('transactionType', models.CharField(default='deposit', max_length=50)),
                ('dateReg', models.DateTimeField(auto_now_add=True)),
                ('regBy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dateReg',),
            },
        ),
    ]
