# Generated by Django 3.0.5 on 2022-01-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('accountNo', models.CharField(max_length=266, primary_key=True, serialize=False, unique=True)),
                ('accountName', models.CharField(max_length=266)),
                ('accountType', models.CharField(max_length=266)),
                ('accountCurrency', models.CharField(default='UGX', max_length=50)),
                ('firstName', models.CharField(max_length=266)),
                ('lastName', models.CharField(max_length=266)),
                ('otherName', models.CharField(blank=True, max_length=266)),
                ('accountStatus', models.CharField(max_length=20)),
                ('balance', models.FloatField(default=0)),
                ('regDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Member Accounts',
            },
        ),
    ]
